sudo: required

env:
  global:
  - REPO=bhavikk/swarm-node-healthcheck
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: Ib7cXkCh8+TIUlG5Qdj6rS7ciEB2sqFZAE2wbZcLbCtEZBiVPQp6clEFDwOakOXxXxAKxCf+AqzDorFp77AYqJdVtIHH4K10Wo9xoftiuPL0UlofayZHSwMa3FAjCrTeNsnCxX/tvRX1cPO+kRTXJPncOv4EcAmu0C9Ent8hiHdsaLn548Fei1ZWJSyjA7q7jDGrZsitOyQfsJ/6g2Q8iUzLlK2LljXoxCKSGJdQUUPN+ejav4zB2PS/8oMaxriEov41hUW5SCG3HvjyCr8YN1VFjnKOxLc9nh1f2fQ12RQBReFL+oFozurYFB4xrL3UAtEqBOGWusLBIzvATL823YbNgFAyGsdSSAPtMANZkz+NrMf1LG7U5mCtwCxoT0YVmTFmuR4hA4CoMXUeT+sbwMraDrSlpGro5kCIp1QGGeIReU9MZrR/oSUSF6drY5eh7M5TsEq6K73SScSFDavJwu8ljtEA1k1bSyu5Ya+PIyN4LHrvuBwd0n7zROiRyR6gc2oKSP0LRu6WIXxiRQz83e4/YKTGFrac+yHLMh0tsFSCt9Im+z1a0MmonDiBdMyxn9URXEd+PSya5uk/6DfoY1KN1sbaApDC6Ld0mEPF2Y4WOcI/ve6X45nvWlOxJeNTe2FF5tAgAajmpk7QF1kWwMZq4nUZwHubSWzfy+NimM8=
  - secure: bIPdwC/a9JeaKzV3ixscXuJNz9zSKBdelkGNmXZ0pShDcIYbHt2sQMn90tybszof8q0r1rnKuqGw6CBvlEUG2JtKKT6OBRfHstGOim/+aidLD0af6EqplSfIasQSVoD3w7TEIuIhDIMPyGjjslqQNfEdDypVrEYMspTrrq/Ivx2L8uyjuZEXt0L0muYA0UYa3Khhxac2p0MnaIo4TMbleja0zYBVrcb2lLIuFBoDUr5THH6Zre9CQs9/KuWXKH+RZ2S+h3Pjo4tfJxtxDwN84fQzDzBXmGXQqun0xDXtNQjMCgyBoBM2LE0PWKXFRYnP1Rk6p+1Rs2hW5TztVKkBJle3F301ws7Gwp4G56p9KsnQhkc9XQ8uGmdt38eLfcScU38FtqnLQolpaPFyjhOCj+4SHV0NW+f3foPrt0uamu7pjYV8CU4GHFfNQP7scOspzeeKpQtpCW0iZV4psnEP8asojV8qvr2rhW57DCkNTZonyqMeEHN1RsbT4o2Tv1gbYufUwG41qRhk1qoAIVmG0Jn9YUtV3I4x9qw9Jrh47h2Fr16ahLGW2/UgkX9ocFT+5dvjmGKQlo/+pXretZwI8eRd3qHXr8dX84+cRuth4ncP8wAiuW3U76xN85MPMfhG+9GjKC0kvrtcnOPbNcAjmmi6LclEVLZF4CBZpgyR4Jc=

language: go

go:
- 1.9

services:
- docker

branches:
  only:
  - master

before_script:
- export TZ=Pacific/Auckland
- export "PATH=/home/travis/gopath/bin:$PATH"
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`

install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure

script:
- go vet -x ./...
- go build -v ./...
- go test -v ./...
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
