sudo: required

env:
  global:
  - REPO=depost/swarm-node-healthcheck
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: MiwqnjqQcUtQvRHaPu7iBSd+ARGEfXUilY/WUl85YO27DF32O+EjfrDF+6JEIkP+YfNMnxQRtknd06++4o3b1C1tnIZeUyYXsRa3HJtFe7/39/WovhPRIzcagFy5nh7Ou9OeF7DClRwINUPFx25HAnkEbiGM22LSvfkCEpYkwIMWM4LJXhH90KLwxzp+FC9176YXh5Qx45QQetE5LbfzUvs/nOFBT64K0heniPtr9xErDh6on1zx+FtC/LYeVxCugPwk153TX38qP3e4M6/sYvA2BUOaH4pkHGYI35wZyP+xxn6dIjsCARi8kbtjK1YGSRdImdFBZdYWthNXGu7mxsQtiC1s0e/O7X8dKyh4eTiwnJOnkLGETUePBH/pkgitXAWsDTd16p3Nj/tP8kLKoCgLPzXMvLp9hfYOBNbX1fNtz7juuecMW4Kqd0WqFw8Jfh6Tuce8eYX4JX1ytJOVFxCut+gBpl7G2zCdB2PeYQDMVBgmDtWRt2xwA+B9Xcj5OUfCSUBVzaPzIgeMfiwkhlOrdjk2MoxSLJObnHvt3n8LZB/T3EBxTbEkD8ZEUoVdOUlzLlbYPhfVx1rvQD+PEx/OTnO+InNWapk3xkW2cXVYVQ/7mFYfqasNc2VqUaNNJblyfjo4Y9CganwJdL3BOKWQoJZk2zWa114hG+3xXVM=
  - secure: LWhlvttolGNvVwaRAmZrFkHWVHbzhFexISJE2h9y6BIUhTVU1+jppE7HWGtbSPRA3WaaM/w3EhqrC7J5cM5m9NSuUnL8ioZ7Qkj2VXYbC1+6B4wFkbosCiIS8uc9RoBhet7JrlDAplTpJpN/6CQVmzbicNi+AEVHcdDA5i905ZFmAx47mIhN3cN2JpyFcZ6vnwdl45EWi6fYdIG0IUW05WUpt2WO3YCTKthvDXmAqKHK+TwvCDw6rtJQ6IHmRPb3sHUqPYuAmC4GFz+haojcDJdHueMc+a2RnNltvvqFXDRzUO+0+ceoT4MoPxneEKP1aouRo7XPjXg1Fck+VgKfvDZ3eNLLsNdpehPGQFf2bzv2bWhfQAfxaA9iPrCaHHblGhvGFmvlPwwCvolSF0lBP6hH0mDMzby0MypxsxXeXjoYMybtnTDuEGBM1L9OxxrBvWIO8caxVEF5Nl2Djxj9uMCDrOzCgaoyAJIeJQO4JHi2jUNruP8hf0MCJbWLCfcf4sgB+T8yHgc/qHI2BTms0CfoJbjkJKo4LqPhrBL7kmrcYQ2NhaLrn82oinBKGbUXH8CZd49QTjdCxX6h3JP8DbeuuHoDLJRFeTN/VilFckf7GHRCCXYODR2DM/OOpnfMd93VEIs3TsoaXDEnyI2TEbrTePu5jJVBXZleCQRRXcg=

language: go

go:
- 1.9

services:
- docker

branches:
  only:
  - master

before_script:
- export TZ=Pacific/Auckland
- export "PATH=/home/travis/gopath/bin:$PATH"
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`

install:
- go get github.com/Masterminds/glide
- glide install

script:
- go vet -x ./...
- go build -v ./...
- go test -v ./...
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
